server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: springstudent
    password: springstudent
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    